name: Run Daily Python Script

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch: 

jobs:
  run-v3-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Script
        run: python v3.py